#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
<<<<<<< HEAD
robotpy_version = "2024.1.1.1"
=======
robotpy_version = "2024.1.1.3"
>>>>>>> 1d85a3431fce30911bdee3fe0061166b6ca7bcfc

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
<<<<<<< HEAD
    # "all"
    # "apriltag"
    # "commands2"
    # "cscore"
    # "navx"
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "rev"
    # "romi"
    # "sim"
    # "xrp"
]

# Other pip packages to install
requires = []
=======
    # "all",
    # "apriltag",
    # "commands2",
    # "cscore",
    # "navx",
    # "pathplannerlib",
    "phoenix5",
    "phoenix6",
    # "playingwithfusion",
    "rev",
    # "romi",
    "sim"
]


# Other pip packages to install
requires = [
    "robotpy-commands-v2==2024.0.0b4"
]
>>>>>>> 1d85a3431fce30911bdee3fe0061166b6ca7bcfc
